// <auto-generated />
using AuctionApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionApp.Migrations
{
    [DbContext(typeof(ListOfBidsDBContext))]
    partial class ListOfBidsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuctionApp.Persistence.BidDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ListOfBidsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<double>("Offer")
                        .HasColumnType("double");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListOfBidsId");

                    b.ToTable("BidDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ListOfBidsId = -1,
                            Name = "Vase",
                            Offer = 100.0,
                            Status = 1
                        },
                        new
                        {
                            Id = -2,
                            ListOfBidsId = -1,
                            Name = "Cat",
                            Offer = 350.0,
                            Status = 1
                        },
                        new
                        {
                            Id = -3,
                            ListOfBidsId = -2,
                            Name = "Rock",
                            Offer = 200.0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("AuctionApp.Persistence.ListOfBidsDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ListOfBidsDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Title = "Winning Bids",
                            UserName = "Jo4r"
                        },
                        new
                        {
                            Id = -2,
                            Title = "Pending Bids",
                            UserName = "Jo4r"
                        });
                });

            modelBuilder.Entity("AuctionApp.Persistence.BidDB", b =>
                {
                    b.HasOne("AuctionApp.Persistence.ListOfBidsDB", "ListOfBidsDb")
                        .WithMany("BidDBs")
                        .HasForeignKey("ListOfBidsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListOfBidsDb");
                });

            modelBuilder.Entity("AuctionApp.Persistence.ListOfBidsDB", b =>
                {
                    b.Navigation("BidDBs");
                });
#pragma warning restore 612, 618
        }
    }
}
